apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-737-2023-t1-prac7c-deployment
  labels:
        app: sit323-737-2023-t1-prac7c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sit323-737-2023-t1-prac7c
  template:
    metadata:
      labels:
        app: sit323-737-2023-t1-prac7c
    spec:
      containers:
        - name: sit323-737-2023-t1-prac7c
          image: mukulksingh98/sit737:latest
          ports:
            - containerPort: 3000
          
